(define (problem astronaut_sample_collection)
  (:domain astronaut_rover)
  (:objects astronaut - agent rover - rover sample - sample location1 - location location2 - location)
  (:init (at astronaut base)
         (at rover base)
         (at astronaut location1)
         (at rover location1)
         (at sample crater)
         (at astronaut location2))
  (:goal (and (at astronaut base)
              (has astronaut sample))))