(define (problem astronaut_collect_problem)
  (:domain astronaut_collect)
  (:objects astronaut - agent rover - object base - location crater - location sample - object)
  (:init (at astronaut base)
         (at rover base)
         (at sample crater)
         (has astronaut sample))
  (:goal (and (at astronaut base)
              (has astronaut sample))))