(define (problem blocks_world_initial)
  (:domain blocks_world)
  (:object-schema (block))
  (:init
    (and (clear table)
         (and (at block1 (location empty-location)) (on-table block1))
         (and (at block2 (location empty-location)) (on-table block2))
         (and (at block3 (location empty-location)) (on-table block3)))
)
(:goal (and (clear table) (and (at block1 (location location1)) (stacked block2 block1) (at block2 (location location2)) (at block3 (location location3))))
)