(define (domain hero-journey)
  (:requirements :strips :typing)
  (:types agent location object monster)
  (:predicates
    (at ?h - agent ?l - location)
    (on_ground ?o - object ?l - location)
    (sleeping ?m - monster)
    (defeated ?m - monster)
    (explored ?l - location)
    (rested ?h - agent)
  )
  (:action move
    :parameters (?h - agent ?from - location ?to - location)
    :precondition (and (at ?h ?from))
    :effect (and (not (at ?h ?from)) (at ?h ?to))
  )
  (:action carry-and-move
    :parameters (?h - agent ?o - object ?from - location ?to - location)
    :precondition (and (at ?h ?from) (on_ground ?o ?from))
    :effect (and (not (at ?h ?from)) (at ?h ?to) (not (on_ground ?o ?from)) (on_ground ?o ?to))
  )
  (:action explore
    :parameters (?h - agent ?l - location)
    :precondition (and (at ?h ?l))
    :effect (explored ?l)
  )
  (:action rest
    :parameters (?h - agent ?l - location)
    :precondition (and (at ?h ?l))
    :effect (rested ?h)
  )
  (:action defeat-forest
    :parameters (?h - agent ?b - monster ?l - location)
    :precondition (and (at ?h ?l) (member ?b (bandit)))
    :effect (defeated ?b)
  )
  (:action defeat-cave
    :parameters (?h - agent ?g - monster ?l - location)
    :precondition (and (at ?h ?l) (member ?g (goblin)))
    :effect (defeated ?g)
  )
  (:action defeat-dragon
    :parameters (?h - agent ?d - monster ?l - location)
    :precondition (and (at ?h ?l) (on_ground sword_of_fire ?l) (sleeping ?d))
    :effect (and (defeated ?d) (not (sleeping ?d)))
  )
)