(define (problem SampleCollectProblem)
  (:domain SampleCollectDomain)
  (:objects astronaut - agent rover - agent sample - object base - location crater - location)
  (:init (at astronaut base)
         (at rover base)
         (at sample crater)
         (at astronaut base)
         (at ?obj - object ?loc - location)
         (at ?obj - object base)
         (at astronaut base)
         (has astronaut sample))
  (:goal (and (at astronaut base)
              (has astronaut sample))))