(define (domain bc-recharge)
  (:requirements :strips :typing :negation)
  (:types robot battery charging-station obstacle)
  (:predicates (at ?x - robot ?y - charging-station)
               (on-ground ?x - battery ?y - charging-station)
               (blocked ?x - obstacle ?y - charging-station))
  (:action reach-charging-station
    :parameters (?robot - robot ?charging-station - charging-station)
    :precondition (and (at ?robot ?charging-station)
                        (on-ground ?battery ?charging-station))
    :effect (and (not (at ?robot ?charging-station))
                (on-ground ?battery ?charging-station)))
  (:action recharge-battery
    :parameters (?robot - robot ?battery - battery)
    :precondition (and (at ?robot ?charging-station)
                        (on-ground ?battery ?charging-station))
    :effect (and (not (on-ground ?battery ?charging-station))
                (not (blocked ?obstacle ?charging-station))))
  (:init (at robot charging-station)
         (on-ground battery charging-station)
         (blocked obstacle charging-station)))