(define (domain Battery-Recharge-Domain)
  (:requirements :strips :typing :adl)
  (:types Robot ChargingStation Battery Obstacle)
  (:predicates (at ?robot ?location)
               (on-ground ?battery ?location)
               (blocked ?obstacle ?location))
  (:action ReachChargingStation
    :parameters (?robot ?charging-station ?battery)
    :precondition (and (at ?robot ?location)
                        (on-ground ?battery ?location)
                        (blocked ?obstacle ?location))
    :effect (and (at ?robot ?charging-station)
                (not (at ?robot ?location))))
  (:action RechargeBattery
    :parameters (?robot ?charging-station ?battery)
    :precondition (and (at ?robot ?charging-station)
                        (on-ground ?battery ?charging-station))
    :effect (and (not (blocked ?obstacle ?location))
                (on-ground ?battery ?location))))