(define (problem robot-problem)
  (:domain robot-domain)
  (:objects robot charging-station battery obstacle)
  (:init (at robot charging-station)
         (on-ground battery charging-station)
         (blocked obstacle charging-station)
         (recharged robot))
  (:goal (and (at robot charging-station) (recharged robot))))
)