(define (problem maze_puzzle)
    (:domain simple_maze)
    (:objects start - location goal - location obstacle1 obstacle2 ... agent1 - agent )
    (:init
      (at agent1 start)
      (clear start)
      (on-table obstacle1)
      (left-of start goal)
      (left-of goal obstacle2)
      (and (adjacent start obstacle1) (not (clear obstacle1)))
      (and (adjacent goal obstacle2) (not (clear obstacle2)))
    )
    (:goal (clear goal))
  )