(define (domain ReachChargingStation)
  (:requirements :strips :typing :fluents)
  (:types robot battery charging-station obstacle)
  (:predicates (at ?x - robot)
               (on-ground ?b - battery)
               (blocked ?o - obstacle)
               (charging-station ?cs - charging-station))
  (:action MoveToChargingStation
    :parameters (?r - robot ?cs - charging-station)
    :precondition (and (at ?r ?o)
                        (on-ground ?b)
                        (blocked ?o))
    :effect (and (not (at ?r ?o))
                (on-ground ?b)))
  (:action PickUpBattery
    :parameters (?r - robot ?cs - charging-station)
    :precondition (and (at ?r ?o)
                        (not (on-ground ?b)))
    :effect (and (on-ground ?b)
                (not (blocked ?o))))
  (:action ChargeBattery
    :parameters (?r - robot ?cs - charging-station)
    :precondition (and (at ?r ?o)
                        (on-ground ?b))
    :effect (and (on-ground ?b)
                (not (blocked ?o))))
  (:action MoveFromChargingStation
    :parameters (?r - robot ?cs - charging-station)
    :precondition (and (at ?r ?cs)
                        (on-ground ?b))
    :effect (and (not (at ?r ?cs))
                (blocked ?o))))